### ISSUE TITLE
Updating from 0.0.1 to 0.1.0 crashes entire test suite

### ISSUE THREAD

**Issue by cope** [Mitscherlich/vitest-localstorage-mock#2]
```
Error: Cannot find module '/builds/my-project/node_modules/.pnpm/vitest-localstorage-mock@0.1.0_vitest@1.3.1/node_modules/vitest-localstorage-mock/lib/localstorage' imported from /builds/my-project/node_modules/.pnpm/vitest-localstorage-mock@0.1.0_vitest@1.3.1/node_modules/vitest-localstorage-mock/lib/setup.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { url: 'file:///C:/git/my-project/node_modules/.pnpm/vitest-localstorage-mock@0.1.0_vitest@1.3.1/node_modules/vitest-localstorage-mock/lib/localstorage', code: 'ERR_MODULE_NOT_FOUND
' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/577]⎯
```
No idea what this `/builds/` folder is, but this error is crashing my entire test suite 😞 

Reverting back to 0.0.1 fixes the problem.

I've also tried to remove globals and add mockReset: false, but it did not help.

**Comment by Mitscherlich** [comment]
Seems `/build/` folder might under your CI/CD system. A full log print or reproducing the repository will provide more helpful information.

Have you tried reinstalling `node_modules`? It seems you might importing the setup scripts manually. I dropped the commonjs support at version 0.1.0. Try to replace with `test.setupFiles` configuration in your
`vite.config.(js|ts)` file.

```js
export default defineConfig({
  test: {
    setupFiles: ['vitest-localstorage-mock'],
  }
})
```

**Comment by cope** [comment]
True, the /build/ is from CI/CD, my bad.
This is the same on my machine
```
Error: Cannot find module 'C:\my-project\node_modules\.pnpm\vitest-localstorage-mock@0.1.0_vitest@1.3.1\node_modules\vitest-localstorage-mock\lib\localstorage' imported from C:\my-project\node_modules\.pnpm\vitest-localstorage-mock@0.1.0_vitest@1.3.1\node_modules\vitest-localstorage-mock\lib\setup.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { url: 'file:///C:/my-project/node_modules/.pnpm/vitest-localstorage-mock@0.1.0_vitest@1.3.1/node_modules/vitest-localstorage-mock/lib/localstorage', code: 'ERR_MODULE_NOT_FOUND
' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/577]⎯
```
I tried deleting node_modules...
I already use `test.setupFiles` configuration in my `vite.config.(js|ts)` file...

The error message basically says that setup.js cannot find localstorage.js which makes no sens since it is right there. I don't get it.

**Comment by Mitscherlich** [comment]
Okay I figured out. This was causing by module resolution in `type: module` package, which forces you specific full filename with extension.

I believe this import statement is causing the crash:

https://github.com/Mitscherlich/vitest-localstorage-mock/blob/6d00c1201b1d51deb46a5506f74dfe06831d900a/lib/setup.js#L2

I just published a new pkg version [`0.1.2`](https://www.npmjs.com/package/vitest-localstorage-mock/v/0.1.2) to fix this issue.

**Comment by cope** [comment]
sry, was at lunch, checking now

**Comment by cope** [comment]
tests already look better

**Comment by cope** [comment]
resolved 💯
